CREATE TABLE `Pr` (
    id BIGINT NOT NULL AUTO_INCREMENT,
    external_id BIGINT NOT NULL,
    number INT NOT NULL,
    author_id BIGINT NOT NULL,
    repository_id BIGINT NOT NULL,
    status ENUM('OPEN','CLOSED') NOT NULL,
    size ENUM('PP','P','M','G','GG') NOT NULL DEFAULT 'M',
    title VARCHAR(255) NULL,
    draft TINYINT(1) NOT NULL DEFAULT 0,
    merged TINYINT(1) NOT NULL DEFAULT 0,
    merged_at DATETIME(6) NULL,
    closed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    infos JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pr_external_id (external_id),
    UNIQUE KEY uk_pr_repo_number (repository_id, number),
    KEY idx_pr_number (number),
    KEY idx_pr_repository_id (repository_id),
    CONSTRAINT fk_pr_user_author FOREIGN KEY (author_id) REFERENCES `User` (id),
    CONSTRAINT fk_pr_repository FOREIGN KEY (repository_id) REFERENCES `Repo` (id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
