CREATE TABLE `Pr` (
    id BIGINT NOT NULL AUTO_INCREMENT,
    github_id BIGINT NOT NULL,
    github_number INT NOT NULL,
    github_author_id BIGINT NOT NULL,
    github_repository_id BIGINT NOT NULL,
    github_status ENUM('OPEN','CLOSED') NOT NULL,
    github_title VARCHAR(255) NULL,
    github_draft TINYINT(1) NOT NULL DEFAULT 0,
    github_merged TINYINT(1) NOT NULL DEFAULT 0,
    github_merged_at DATETIME(6) NULL,
    github_closed_at DATETIME(6) NULL,
    github_created_at DATETIME(6) NOT NULL,
    github_updated_at DATETIME(6) NOT NULL,
    infos JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pr_github_id (github_id),
    UNIQUE KEY uk_pr_repo_number (github_repository_id, github_number),
    KEY idx_pr_github_number (github_number),
    KEY idx_pr_github_repository_id (github_repository_id),
    CONSTRAINT fk_pr_user_author FOREIGN KEY (github_author_id) REFERENCES `User` (id),
    CONSTRAINT fk_pr_github_repository FOREIGN KEY (github_repository_id) REFERENCES `Repo` (id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
